### ISSUE TITLE
should should be valid *** FAILED *** com.google.inject.ConfigurationException: Guice configuration errors: 1) Could not find a suitable constructor in se.radley.plugin.salat.SalatPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private. at se.radley.plugin.salat.SalatPlugin.class(SalatPlugin.scala:12) while locating se.radley.plugin.salat.SalatPlugin

### ISSUE THREAD

**Issue by sprakasam** [leon/play-salat#67]

**Comment by sprakasam** [comment]
should should be valid *** FAILED *** com.google.inject.ConfigurationException: Guice configuration errors: 1) Could not find a suitable constructor in se.radley.plugin.salat.SalatPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private. at se.radley.plugin.salat.SalatPlugin.class(SalatPlugin.scala:12) while locating se.radley.plugin.salat.SalatPlugin

**Comment by sevenfrost** [comment]
same here
